### ISSUE TITLE
Looks promising but... many bugs.

### ISSUE THREAD

**Issue by superdeeid** [RaggiTech/pharaoh-http#1]
Just installed your class with composer... Here some corrections:

- wrong namespace : \RaggiTech\... should be \Pharaoh\...
- your url section should be $request->url->current() not $request->current()
- Globally, test your read me instructions... ;)

Again, it's very promising. Loving it! I was just thinking about doing that for my upcoming projects. Congrats !

**Comment by RaggiTech** [comment]
**Thank you so much @superdeeid** for your help.
i will be really more happier if you find another bugs <3

**Comment by RaggiTech** [comment]
**Thank you so much @superdeeid for your help.
i will be really more happier if you find another bugs <3**
